import { NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabParamList } from "./BottomTabParamList";

export type RootStackParamList = {
    DrawerNavigation: NavigatorScreenParams<BottomTabParamList>;
    Damo: undefined;
    splash: undefined;
    ChooseLanguage:{ data?: any };
    QrCodeScanner: undefined;
    UserSignUp: undefined;
    MerchantSignUp: undefined;
    SignIn: undefined;
    Onbording: undefined;
    ComplateProfile: undefined;
    Login: undefined;
    Register: undefined;
    ForgatPassword: undefined;
    EnterCode: undefined;
    LookingFor: undefined;
    ExperienceLevel: undefined;
    workingModel: undefined;
    Allowlocation: undefined;
    LookingToObtain: undefined;
    EmailVerify: undefined;
    NewPassword: undefined;
    ResetPassword: undefined;
    Settings: undefined;
    NotificationSettings: undefined;
    Allownotification: undefined;
    HelpCenter: undefined;
    ChangePassword: undefined;
    TwoStepAuthentication: undefined;
    FindLocation: undefined;
    BottomNavigation: undefined;
    SingleChat:{ data?: any };
    Messages: undefined;
    Support: undefined;
    History: undefined;
    Verification: undefined;
    Call: undefined;
    EditProfile: undefined;
    ProfileBasicDetails: undefined;
    Profilesummary: undefined;
    ProfessionalDetails: undefined;
    Employment: undefined;
    Education: undefined;
    ProfileProjects: undefined;
    ProfileSkills: undefined;
    ProfileUploadResume: undefined;
    WriteReview: undefined;
    Trackorder: undefined;
    Products: undefined;
    Language: { data?: any };
    MyCart: undefined;
    Category: undefined;
    Notifications: undefined;
    Questions: undefined;
    JobDetails:{ data?: any };
    Writereview: undefined;
    Profile: undefined;
    SaveJob: { data?: any };
    Search: undefined;
    SearchResults: undefined;
    JobApplied: undefined;
    AboutCompany: { data?: any }; 
    AboutGalary: undefined;
    Components: undefined;
    Coupons: undefined;
    SavedAddresses: undefined;
    Checkout: undefined;
    Addcard: undefined;
    Payment: undefined;
    SaveAddress: undefined;
    Myorder: undefined;
    MyApplication: undefined;
    MyApplicationStatus: { data?: any };
    ContactUs: { data?: any };
    AddCard: undefined;
    Notification: undefined;
    Home: undefined;
    Dashboard: undefined;
    CameraComponent: undefined;
    Accordion: undefined;
    ActionModals: undefined;
    BottomSheet: undefined;
    ModalBox: undefined;
    Buttons: undefined;
    Badges: undefined;
    Charts: undefined;
    Headers: undefined;
    lists: undefined;
    Pricings: undefined;
    DividerElements: undefined;
    Snackbars: undefined;
    Socials: undefined;
    Swipeable: undefined;
    Tabs: undefined;
    Tables: undefined;
    Toggles: undefined;
    Inputs: undefined;
    Footers: undefined;
    TabStyle1: undefined;
    TabStyle2: undefined;
    TabStyle3: undefined;
    TabStyle4: undefined;
    Datepicker: undefined;
    Search2: undefined;
    WebViewer: { url: string };
};